#spring.application.name=Project07-ProfilesWith-YMLFiles

#prod
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: NARESH
    password: NARESH
